name: covid-19-community 

channels:
  - conda-forge
  - anaconda
  - esri
  - bioconda

dependencies:
  - python=3.7
  - openjdk=11.0.1
  - jupyterlab=3
  - jupyter-offlinenotebook
  - pandas=1.3.5
  - dask
  - aiohttp
  - requests
  - xlrd
  - openpyxl=2.6.0
  - lxml
  - python-libsbml=5.18.0
  - matplotlib
  - matplotlib-venn
  - seaborn=0.11.0
  - biopython
  - papermill=2.1.0
  - ipywidgets=7.6.2
  - ipycytoscape>=1.0.3
  - scikit-learn=0.23.2
  - arcgis=1.8.1
  - py3Dmol=0.8.0
  - unidecode
  - pyvcf
  - plotly=5.5.0
  - py2neo 
  - monotonic
